
[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/knative/pkg"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.3.0"

[[constraint]]
  branch = "release-branch.go1.10"
  name = "golang.org/x/net"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.13.0"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "1.13.4"

[prune]
  go-tests = true
  unused-packages = true
