// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dispatcher.proto

package dispatcher

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Operation int32

const (
	Operation_DEFAULT Operation = 0
	Operation_INTRO   Operation = 1
	Operation_CONNECT Operation = 2
	Operation_LISTEN  Operation = 3
	Operation_SOCKET  Operation = 4
)

var Operation_name = map[int32]string{
	0: "DEFAULT",
	1: "INTRO",
	2: "CONNECT",
	3: "LISTEN",
	4: "SOCKET",
}
var Operation_value = map[string]int32{
	"DEFAULT": 0,
	"INTRO":   1,
	"CONNECT": 2,
	"LISTEN":  3,
	"SOCKET":  4,
}

func (x Operation) String() string {
	return proto.EnumName(Operation_name, int32(x))
}
func (Operation) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dispatcher_e68cbf5c61bdd2b1, []int{0}
}

type ID struct {
	PodName              string   `protobuf:"bytes,1,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	PodNamespace         string   `protobuf:"bytes,2,opt,name=pod_namespace,json=podNamespace,proto3" json:"pod_namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ID) Reset()         { *m = ID{} }
func (m *ID) String() string { return proto.CompactTextString(m) }
func (*ID) ProtoMessage()    {}
func (*ID) Descriptor() ([]byte, []int) {
	return fileDescriptor_dispatcher_e68cbf5c61bdd2b1, []int{0}
}
func (m *ID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ID.Unmarshal(m, b)
}
func (m *ID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ID.Marshal(b, m, deterministic)
}
func (dst *ID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ID.Merge(dst, src)
}
func (m *ID) XXX_Size() int {
	return xxx_messageInfo_ID.Size(m)
}
func (m *ID) XXX_DiscardUnknown() {
	xxx_messageInfo_ID.DiscardUnknown(m)
}

var xxx_messageInfo_ID proto.InternalMessageInfo

func (m *ID) GetPodName() string {
	if m != nil {
		return m.PodName
	}
	return ""
}

func (m *ID) GetPodNamespace() string {
	if m != nil {
		return m.PodNamespace
	}
	return ""
}

// Intro message is sent from a client to the dispatcher to announce
// its presence on the node.
type IntroMsg struct {
	PodId                *ID      `protobuf:"bytes,1,opt,name=pod_id,json=podId,proto3" json:"pod_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IntroMsg) Reset()         { *m = IntroMsg{} }
func (m *IntroMsg) String() string { return proto.CompactTextString(m) }
func (*IntroMsg) ProtoMessage()    {}
func (*IntroMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_dispatcher_e68cbf5c61bdd2b1, []int{1}
}
func (m *IntroMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntroMsg.Unmarshal(m, b)
}
func (m *IntroMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntroMsg.Marshal(b, m, deterministic)
}
func (dst *IntroMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntroMsg.Merge(dst, src)
}
func (m *IntroMsg) XXX_Size() int {
	return xxx_messageInfo_IntroMsg.Size(m)
}
func (m *IntroMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_IntroMsg.DiscardUnknown(m)
}

var xxx_messageInfo_IntroMsg proto.InternalMessageInfo

func (m *IntroMsg) GetPodId() *ID {
	if m != nil {
		return m.PodId
	}
	return nil
}

// Connect message is sent by the client which wants to build memif connection
// to another pod which is in Listen mode.
type ConnectMsg struct {
	SrcId                *ID      `protobuf:"bytes,1,opt,name=src_id,json=srcId,proto3" json:"src_id,omitempty"`
	DstId                *ID      `protobuf:"bytes,2,opt,name=dst_id,json=dstId,proto3" json:"dst_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectMsg) Reset()         { *m = ConnectMsg{} }
func (m *ConnectMsg) String() string { return proto.CompactTextString(m) }
func (*ConnectMsg) ProtoMessage()    {}
func (*ConnectMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_dispatcher_e68cbf5c61bdd2b1, []int{2}
}
func (m *ConnectMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectMsg.Unmarshal(m, b)
}
func (m *ConnectMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectMsg.Marshal(b, m, deterministic)
}
func (dst *ConnectMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectMsg.Merge(dst, src)
}
func (m *ConnectMsg) XXX_Size() int {
	return xxx_messageInfo_ConnectMsg.Size(m)
}
func (m *ConnectMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectMsg proto.InternalMessageInfo

func (m *ConnectMsg) GetSrcId() *ID {
	if m != nil {
		return m.SrcId
	}
	return nil
}

func (m *ConnectMsg) GetDstId() *ID {
	if m != nil {
		return m.DstId
	}
	return nil
}

// Listen message is sent by the the client which wants to listen for incoming
// memif connection. Usually a server type application.
type ListenMsg struct {
	ListenerId           *ID      `protobuf:"bytes,1,opt,name=listener_id,json=listenerId,proto3" json:"listener_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListenMsg) Reset()         { *m = ListenMsg{} }
func (m *ListenMsg) String() string { return proto.CompactTextString(m) }
func (*ListenMsg) ProtoMessage()    {}
func (*ListenMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_dispatcher_e68cbf5c61bdd2b1, []int{3}
}
func (m *ListenMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListenMsg.Unmarshal(m, b)
}
func (m *ListenMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListenMsg.Marshal(b, m, deterministic)
}
func (dst *ListenMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListenMsg.Merge(dst, src)
}
func (m *ListenMsg) XXX_Size() int {
	return xxx_messageInfo_ListenMsg.Size(m)
}
func (m *ListenMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ListenMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ListenMsg proto.InternalMessageInfo

func (m *ListenMsg) GetListenerId() *ID {
	if m != nil {
		return m.ListenerId
	}
	return nil
}

// Socket message is sent by the dispatcher to both client and server with the sockets
// they have to use to build memif connection
type SocketMsg struct {
	PodId                *ID      `protobuf:"bytes,1,opt,name=pod_id,json=podId,proto3" json:"pod_id,omitempty"`
	Fd                   int64    `protobuf:"varint,2,opt,name=fd,proto3" json:"fd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SocketMsg) Reset()         { *m = SocketMsg{} }
func (m *SocketMsg) String() string { return proto.CompactTextString(m) }
func (*SocketMsg) ProtoMessage()    {}
func (*SocketMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_dispatcher_e68cbf5c61bdd2b1, []int{4}
}
func (m *SocketMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SocketMsg.Unmarshal(m, b)
}
func (m *SocketMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SocketMsg.Marshal(b, m, deterministic)
}
func (dst *SocketMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SocketMsg.Merge(dst, src)
}
func (m *SocketMsg) XXX_Size() int {
	return xxx_messageInfo_SocketMsg.Size(m)
}
func (m *SocketMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_SocketMsg.DiscardUnknown(m)
}

var xxx_messageInfo_SocketMsg proto.InternalMessageInfo

func (m *SocketMsg) GetPodId() *ID {
	if m != nil {
		return m.PodId
	}
	return nil
}

func (m *SocketMsg) GetFd() int64 {
	if m != nil {
		return m.Fd
	}
	return 0
}

// Reply message is sent by the dispatcher as a confirmation echoing requesting pod
// id and operation, extended error may contain additional information is success is false
type ReplyMsg struct {
	PodId                *ID       `protobuf:"bytes,1,opt,name=pod_id,json=podId,proto3" json:"pod_id,omitempty"`
	Op                   Operation `protobuf:"varint,2,opt,name=op,proto3,enum=dispatcher.Operation" json:"op,omitempty"`
	Success              bool      `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	ExtendedError        string    `protobuf:"bytes,4,opt,name=extended_error,json=extendedError,proto3" json:"extended_error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ReplyMsg) Reset()         { *m = ReplyMsg{} }
func (m *ReplyMsg) String() string { return proto.CompactTextString(m) }
func (*ReplyMsg) ProtoMessage()    {}
func (*ReplyMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_dispatcher_e68cbf5c61bdd2b1, []int{5}
}
func (m *ReplyMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyMsg.Unmarshal(m, b)
}
func (m *ReplyMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyMsg.Marshal(b, m, deterministic)
}
func (dst *ReplyMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyMsg.Merge(dst, src)
}
func (m *ReplyMsg) XXX_Size() int {
	return xxx_messageInfo_ReplyMsg.Size(m)
}
func (m *ReplyMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyMsg proto.InternalMessageInfo

func (m *ReplyMsg) GetPodId() *ID {
	if m != nil {
		return m.PodId
	}
	return nil
}

func (m *ReplyMsg) GetOp() Operation {
	if m != nil {
		return m.Op
	}
	return Operation_DEFAULT
}

func (m *ReplyMsg) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ReplyMsg) GetExtendedError() string {
	if m != nil {
		return m.ExtendedError
	}
	return ""
}

func init() {
	proto.RegisterType((*ID)(nil), "dispatcher.ID")
	proto.RegisterType((*IntroMsg)(nil), "dispatcher.IntroMsg")
	proto.RegisterType((*ConnectMsg)(nil), "dispatcher.ConnectMsg")
	proto.RegisterType((*ListenMsg)(nil), "dispatcher.ListenMsg")
	proto.RegisterType((*SocketMsg)(nil), "dispatcher.SocketMsg")
	proto.RegisterType((*ReplyMsg)(nil), "dispatcher.ReplyMsg")
	proto.RegisterEnum("dispatcher.Operation", Operation_name, Operation_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DispatcherClient is the client API for Dispatcher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DispatcherClient interface {
	Socket(ctx context.Context, in *SocketMsg, opts ...grpc.CallOption) (*ReplyMsg, error)
	Intro(ctx context.Context, in *IntroMsg, opts ...grpc.CallOption) (*ReplyMsg, error)
	Connect(ctx context.Context, in *ConnectMsg, opts ...grpc.CallOption) (*ReplyMsg, error)
	Listen(ctx context.Context, in *ListenMsg, opts ...grpc.CallOption) (*ReplyMsg, error)
}

type dispatcherClient struct {
	cc *grpc.ClientConn
}

func NewDispatcherClient(cc *grpc.ClientConn) DispatcherClient {
	return &dispatcherClient{cc}
}

func (c *dispatcherClient) Socket(ctx context.Context, in *SocketMsg, opts ...grpc.CallOption) (*ReplyMsg, error) {
	out := new(ReplyMsg)
	err := c.cc.Invoke(ctx, "/dispatcher.Dispatcher/Socket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dispatcherClient) Intro(ctx context.Context, in *IntroMsg, opts ...grpc.CallOption) (*ReplyMsg, error) {
	out := new(ReplyMsg)
	err := c.cc.Invoke(ctx, "/dispatcher.Dispatcher/Intro", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dispatcherClient) Connect(ctx context.Context, in *ConnectMsg, opts ...grpc.CallOption) (*ReplyMsg, error) {
	out := new(ReplyMsg)
	err := c.cc.Invoke(ctx, "/dispatcher.Dispatcher/Connect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dispatcherClient) Listen(ctx context.Context, in *ListenMsg, opts ...grpc.CallOption) (*ReplyMsg, error) {
	out := new(ReplyMsg)
	err := c.cc.Invoke(ctx, "/dispatcher.Dispatcher/Listen", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DispatcherServer is the server API for Dispatcher service.
type DispatcherServer interface {
	Socket(context.Context, *SocketMsg) (*ReplyMsg, error)
	Intro(context.Context, *IntroMsg) (*ReplyMsg, error)
	Connect(context.Context, *ConnectMsg) (*ReplyMsg, error)
	Listen(context.Context, *ListenMsg) (*ReplyMsg, error)
}

func RegisterDispatcherServer(s *grpc.Server, srv DispatcherServer) {
	s.RegisterService(&_Dispatcher_serviceDesc, srv)
}

func _Dispatcher_Socket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SocketMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatcherServer).Socket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dispatcher.Dispatcher/Socket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatcherServer).Socket(ctx, req.(*SocketMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dispatcher_Intro_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntroMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatcherServer).Intro(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dispatcher.Dispatcher/Intro",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatcherServer).Intro(ctx, req.(*IntroMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dispatcher_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatcherServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dispatcher.Dispatcher/Connect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatcherServer).Connect(ctx, req.(*ConnectMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dispatcher_Listen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListenMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatcherServer).Listen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dispatcher.Dispatcher/Listen",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatcherServer).Listen(ctx, req.(*ListenMsg))
	}
	return interceptor(ctx, in, info, handler)
}

var _Dispatcher_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dispatcher.Dispatcher",
	HandlerType: (*DispatcherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Socket",
			Handler:    _Dispatcher_Socket_Handler,
		},
		{
			MethodName: "Intro",
			Handler:    _Dispatcher_Intro_Handler,
		},
		{
			MethodName: "Connect",
			Handler:    _Dispatcher_Connect_Handler,
		},
		{
			MethodName: "Listen",
			Handler:    _Dispatcher_Listen_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dispatcher.proto",
}

func init() { proto.RegisterFile("dispatcher.proto", fileDescriptor_dispatcher_e68cbf5c61bdd2b1) }

var fileDescriptor_dispatcher_e68cbf5c61bdd2b1 = []byte{
	// 419 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x5d, 0x6b, 0xd4, 0x40,
	0x14, 0x35, 0xb3, 0xdd, 0x7c, 0xdc, 0xb5, 0x21, 0x0c, 0x2a, 0xd1, 0xa7, 0x12, 0x59, 0x28, 0x3e,
	0x54, 0xdc, 0x52, 0x7c, 0xf1, 0x45, 0x93, 0x88, 0x83, 0x6b, 0x02, 0xd9, 0xf8, 0xe2, 0x4b, 0x89,
	0x33, 0x53, 0x0d, 0xb6, 0x99, 0x61, 0x66, 0x04, 0xfd, 0x29, 0xfe, 0x43, 0x7f, 0x86, 0x64, 0x76,
	0x93, 0x66, 0xa1, 0x2b, 0xfa, 0x96, 0x7b, 0xee, 0x39, 0x87, 0x93, 0x9b, 0x13, 0x88, 0x58, 0xab,
	0x65, 0x63, 0xe8, 0x57, 0xae, 0xce, 0xa4, 0x12, 0x46, 0x60, 0xb8, 0x45, 0x92, 0x0c, 0x10, 0xc9,
	0xf0, 0x63, 0xf0, 0xa5, 0x60, 0x97, 0x5d, 0x73, 0xc3, 0x63, 0xe7, 0xc4, 0x39, 0x0d, 0x2a, 0x4f,
	0x0a, 0x56, 0x34, 0x37, 0x1c, 0x3f, 0x85, 0xe3, 0x61, 0xa5, 0x65, 0x43, 0x79, 0x8c, 0xec, 0xfe,
	0xfe, 0x6e, 0x6f, 0xb1, 0xe4, 0x05, 0xf8, 0xa4, 0x33, 0x4a, 0x7c, 0xd0, 0x5f, 0xf0, 0x12, 0xdc,
	0x5e, 0xd0, 0x32, 0xeb, 0xb4, 0x58, 0x85, 0x67, 0x93, 0x00, 0x24, 0xab, 0xe6, 0x52, 0x30, 0xc2,
	0x92, 0x4f, 0x00, 0xa9, 0xe8, 0x3a, 0x4e, 0xcd, 0x4e, 0xa4, 0x15, 0xfd, 0x8b, 0x48, 0x2b, 0x4a,
	0x58, 0x4f, 0x63, 0xda, 0xf4, 0x34, 0x74, 0x37, 0x8d, 0x69, 0x43, 0x58, 0xf2, 0x0a, 0x82, 0x75,
	0xab, 0x0d, 0xef, 0x7a, 0xeb, 0xe7, 0xb0, 0xb8, 0xb6, 0x03, 0x57, 0x87, 0xfd, 0x61, 0xa0, 0x10,
	0x96, 0xbc, 0x81, 0x60, 0x23, 0xe8, 0x37, 0x6e, 0xfe, 0xfd, 0x6d, 0x70, 0x08, 0xe8, 0x6a, 0x1b,
	0x6a, 0x56, 0xa1, 0x2b, 0x96, 0xfc, 0x72, 0xc0, 0xaf, 0xb8, 0xbc, 0xfe, 0xf9, 0x1f, 0x1e, 0x4b,
	0x40, 0x42, 0x5a, 0x8f, 0x70, 0xf5, 0x70, 0x4a, 0x29, 0x25, 0x57, 0x8d, 0x69, 0x45, 0x57, 0x21,
	0x21, 0x71, 0x0c, 0x9e, 0xfe, 0x4e, 0x29, 0xd7, 0x3a, 0x9e, 0x9d, 0x38, 0xa7, 0x7e, 0x35, 0x8c,
	0x78, 0x09, 0x21, 0xff, 0x61, 0x78, 0xc7, 0x38, 0xbb, 0xe4, 0x4a, 0x09, 0x15, 0x1f, 0xd9, 0x6f,
	0x75, 0x3c, 0xa0, 0x79, 0x0f, 0x3e, 0x7b, 0x07, 0xc1, 0xe8, 0x88, 0x17, 0xe0, 0x65, 0xf9, 0xdb,
	0xd7, 0x1f, 0xd7, 0x75, 0x74, 0x0f, 0x07, 0x30, 0x27, 0x45, 0x5d, 0x95, 0x91, 0xd3, 0xe3, 0x69,
	0x59, 0x14, 0x79, 0x5a, 0x47, 0x08, 0x03, 0xb8, 0x6b, 0xb2, 0xa9, 0xf3, 0x22, 0x9a, 0xf5, 0xcf,
	0x9b, 0x32, 0x7d, 0x9f, 0xd7, 0xd1, 0xd1, 0xea, 0xb7, 0x03, 0x90, 0x8d, 0x39, 0xf1, 0x05, 0xb8,
	0xdb, 0xc3, 0xe1, 0xbd, 0xf8, 0xe3, 0x31, 0x9f, 0x3c, 0x98, 0xc2, 0xe3, 0x79, 0xce, 0x61, 0x6e,
	0xcb, 0x83, 0xf7, 0xd6, 0x43, 0x9f, 0x0e, 0x88, 0x5e, 0x82, 0xb7, 0xab, 0x0f, 0x7e, 0x34, 0x25,
	0xdc, 0x76, 0xea, 0x80, 0xf0, 0x02, 0xdc, 0x6d, 0x37, 0xf6, 0x43, 0x8e, 0x7d, 0xb9, 0x5b, 0xf6,
	0xd9, 0xb5, 0xbf, 0xce, 0xf9, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x42, 0x65, 0x71, 0xb5, 0x4e,
	0x03, 0x00, 0x00,
}
