---
apiVersion: apps/v1
kind: Deployment
spec:
  selector:
    matchLabels:
      app: listen
  replicas: 1
  template:
    metadata:
      labels:
        app: listen
    spec:
      containers:
        - image: docker.io/sbezverk/memif-listen:0.0.0
          name: connect
          imagePullPolicy: Always
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: memif-socket
              mountPath: /var/lib/memif-dispatch
      volumes:
        - hostPath:
            path: /var/lib/memif-dispatch
            type: DirectoryOrCreate
          name: memif-socket
metadata:
  name: listen
  namespace: default
