---
apiVersion: apps/v1
kind: Deployment
spec:
  selector:
    matchLabels:
      app: listen
  replicas: 1
  template:
    metadata:
      labels:
        app: listen
    spec:
      containers:
        - image: docker.io/sbezverk/listen:0.0.0
          name: listen
          imagePullPolicy: Always
          args:
            - --svc-id
            - "service-1_1"
            - --max-connections
            - "50"
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: socket
              mountPath: /var/lib/dispatch
      volumes:
        - hostPath:
            path: /var/lib/dispatch
            type: DirectoryOrCreate
          name: socket
metadata:
  name: listen
  namespace: default
